import { after, test } from 'node:test'
import assert from 'node:assert/strict'
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
// @ts-expect-error — plain-JS analysis module, no type declarations.
import { CLEANROOM_ARTIFACTS, CLEANROOM_SCHEMA_VERSION, cleanroomArtifactSetSha256, cleanroomRegenerationPlan, runCleanroom, verifyCleanroomAttestation } from '../../../scripts/build-cleanroom-v3.mjs'

const dirs: string[] = []
after(() => { for (const dir of dirs) rmSync(dir, { recursive: true, force: true }) })

function fixture() {
  const dir = mkdtempSync(join(tmpdir(), 'cleanroom-v3-test-'))
  dirs.push(dir)
  const runDir = join(dir, 'run')
  const logs = join(dir, 'logs')
  const manifest = join(runDir, 'manifest.json')
  const provenance = join(runDir, 'handcheck', 'pf2-provenance.json')
  const out = join(runDir, 'cleanroom.json')
  mkdirSync(logs, { recursive: true })
  mkdirSync(dirname(provenance), { recursive: true })
  writeFileSync(manifest, '{"fixture":true}\n')
  writeFileSync(provenance, '{"fixture":true}\n')
  for (const [index, label] of CLEANROOM_ARTIFACTS.entries()) {
    const path = join(runDir, label)
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, `artifact ${index}: ${label}\n`)
  }
  const manifestValue = {
    analysisRunId: 'a'.repeat(64),
    codeCommit: 'b'.repeat(40),
    logs: { count: 40, files: {} },
    bootstrap: { seed: 'fixture-bootstrap', replicates: 20 },
  }
  const deps = {
    loadManifest: () => manifestValue,
    verifyManifest: () => ({ ok: true, errors: [] }),
    currentGitHead: () => manifestValue.codeCommit,
    assertCommittedAnalysisTree: () => undefined,
  }
  return { dir, runDir, logs, manifest, provenance, out, manifestValue, deps }
}

function copyExpected(runDir: string, temporaryRunDir: string) {
  for (const label of CLEANROOM_ARTIFACTS) {
    const target = join(temporaryRunDir, label)
    mkdirSync(dirname(target), { recursive: true })
    copyFileSync(join(runDir, label), target)
  }
}

test('clean-room attestation is written only after every fixed artifact matches byte-for-byte', () => {
  const c = fixture()
  let temporaryRunDir = ''
  const report = runCleanroom({
    manifest: c.manifest,
    runDir: c.runDir,
    logs: c.logs,
    provenance: c.provenance,
    out: c.out,
  }, {
    ...c.deps,
    regenerate: (context: { temporaryRunDir: string }) => {
      temporaryRunDir = context.temporaryRunDir
      copyExpected(c.runDir, context.temporaryRunDir)
    },
  })

  assert.equal(report.ok, true)
  assert.equal(report.schemaVersion, CLEANROOM_SCHEMA_VERSION)
  assert.equal(report.analysisRunId, c.manifestValue.analysisRunId)
  assert.equal(report.codeCommit, c.manifestValue.codeCommit)
  assert.equal(report.artifactCount, CLEANROOM_ARTIFACTS.length)
  assert.deepEqual(report.reproduced.map((row: { path: string }) => row.path), CLEANROOM_ARTIFACTS)
  assert.equal(report.artifactSetSha256, cleanroomArtifactSetSha256(report.reproduced))
  assert.deepEqual(JSON.parse(readFileSync(c.out, 'utf8')), report)
  assert.deepEqual(verifyCleanroomAttestation({
    report,
    manifest: c.manifestValue,
    manifestPath: c.manifest,
    runDir: c.runDir,
    provenance: c.provenance,
    headResolver: c.deps.currentGitHead,
    committedTreeVerifier: c.deps.assertCommittedAnalysisTree,
  }), { ok: true, artifacts: CLEANROOM_ARTIFACTS.length })
  assert.equal(existsSync(temporaryRunDir), false, 'fresh regeneration directory is removed after attestation')
})

test('one changed regenerated byte refuses the run and leaves no ok attestation', () => {
  const c = fixture()
  let temporaryRunDir = ''
  writeFileSync(c.out, '{"ok":true,"stale":true}\n')
  assert.throws(() => runCleanroom({
    manifest: c.manifest,
    runDir: c.runDir,
    logs: c.logs,
    provenance: c.provenance,
    out: c.out,
  }, {
    ...c.deps,
    regenerate: (context: { temporaryRunDir: string }) => {
      temporaryRunDir = context.temporaryRunDir
      copyExpected(c.runDir, context.temporaryRunDir)
      writeFileSync(join(context.temporaryRunDir, CLEANROOM_ARTIFACTS[4]), 'tampered\n')
    },
  }), /clean-room bytes differ/)
  assert.equal(existsSync(c.out), false, 'a failed comparison removes stale success and creates no attestation')
  assert.equal(existsSync(temporaryRunDir), false, 'fresh regeneration directory is removed after failure')
})

test('saved attestation refuses a publication artifact changed after the clean-room pass', () => {
  const c = fixture()
  const report = runCleanroom({
    manifest: c.manifest,
    runDir: c.runDir,
    logs: c.logs,
    provenance: c.provenance,
    out: c.out,
  }, {
    ...c.deps,
    regenerate: (context: { temporaryRunDir: string }) => copyExpected(c.runDir, context.temporaryRunDir),
  })
  writeFileSync(join(c.runDir, CLEANROOM_ARTIFACTS[8]), 'changed after attestation\n')
  assert.throws(() => verifyCleanroomAttestation({
    report,
    manifest: c.manifestValue,
    manifestPath: c.manifest,
    runDir: c.runDir,
    provenance: c.provenance,
    headResolver: c.deps.currentGitHead,
    committedTreeVerifier: c.deps.assertCommittedAnalysisTree,
  }), /current bytes differ/)
})

test('saved attestation refuses a different checkout HEAD', () => {
  const c = fixture()
  const report = runCleanroom({
    manifest: c.manifest,
    runDir: c.runDir,
    logs: c.logs,
    provenance: c.provenance,
    out: c.out,
  }, {
    ...c.deps,
    regenerate: (context: { temporaryRunDir: string }) => copyExpected(c.runDir, context.temporaryRunDir),
  })
  assert.throws(() => verifyCleanroomAttestation({
    report,
    manifest: c.manifestValue,
    manifestPath: c.manifest,
    runDir: c.runDir,
    provenance: c.provenance,
    headResolver: () => 'c'.repeat(40),
    committedTreeVerifier: c.deps.assertCommittedAnalysisTree,
  }), /current HEAD.*does not match/)
})

test('regeneration plan uses all real builders and the manifest bootstrap count', () => {
  const plan = cleanroomRegenerationPlan({
    manifest: '/frozen/manifest.json',
    runDir: '/frozen/run',
    logs: '/frozen/logs',
    provenance: '/frozen/run/handcheck/pf2-provenance.json',
    temporaryRunDir: '/fresh/run',
    bootstrapReplicates: 20_000,
  })
  assert.equal(plan.length, CLEANROOM_ARTIFACTS.length)
  assert.deepEqual(plan.map((step: { program: string }) => step.program.split('/').at(-1)), [
    'merge-packet-rulings.mjs',
    'opportunity-table.mjs',
    'build-ledger.mjs', 'build-ledger.mjs', 'build-ledger.mjs',
    'stats-v3.mjs', 'stats-v3.mjs', 'stats-v3.mjs',
    'agreement.mjs',
    'build-pf2-validation.mjs',
    'build-sensitivity-v3.mjs',
  ])
  const statsSteps = plan.filter((step: { program: string }) => step.program.endsWith('/stats-v3.mjs'))
  for (const step of statsSteps) {
    const index = step.args.indexOf('--bootstrap-n')
    assert.equal(step.args[index + 1], '20000')
  }
  assert.ok(plan.every((step: { args: string[] }) => step.args.includes('/fresh/run') || step.args.some((arg) => arg.startsWith('/fresh/run/'))),
    'every builder writes into the fresh temporary run')
})

test('manifest codeCommit must equal current HEAD before regeneration starts', () => {
  const c = fixture()
  let called = false
  assert.throws(() => runCleanroom({
    manifest: c.manifest,
    runDir: c.runDir,
    logs: c.logs,
    provenance: c.provenance,
    out: c.out,
  }, {
    ...c.deps,
    currentGitHead: () => 'c'.repeat(40),
    regenerate: () => { called = true },
  }), /does not match current HEAD/)
  assert.equal(called, false)
  assert.equal(existsSync(c.out), false)
})
